.PHONY=all
all: 2dca.js elementary_ca.js

2dca.js: ../coffee/2dca.coffee
	coffee -m -o ./ ../coffee/2dca.coffee
elementary_ca.js: ../coffee/elementary_ca.coffee
	coffee -m -o ./ ../coffee/elementary_ca.coffee
